#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d web msg music files V VI VII VII
bspc config border_width          2
bspc config window_gap            12
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Border Colors
bspc config focused_border_color "#1b1f20"
bspc config presel_feedback_color "#d8b4bd"
bspc config top_padding 40

# Define Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Auto start stuff
~/.config/polybar/launch.sh &
picom &
dunst ~/.config/dunst/dunstrc &
xfce4-power-manager &
xsetroot -cursor_name left_ptr &
setxkbmap es &
nitrogen --restore &
